<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="secbpmn2bc" nsURI="http://it.polimi.isgroup.secbpmn2bc.model/1.0"
    nsPrefix="secbpmn2bc">
  <eClassifiers xsi:type="ecore:EClass" name="PrivitySphere" eSuperTypes="http://localhost:8080/secbpmn.ecore#//SecurityAnnotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Scope" lowerBound="1" eType="#//PrivityScope"
        defaultValueLiteral="Public"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enforceability" eSuperTypes="http://localhost:8080/secbpmn.ecore#//SecurityAnnotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Scope" lowerBound="1" eType="#//EnforceabilityScope"
        defaultValueLiteral="Public"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="UserDefinedUsers" upperBound="-1"
        eType="ecore:EClass http://localhost:8080/secbpmn.ecore#//User"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnforceabilityScope">
    <eLiterals name="Public"/>
    <eLiterals name="Private" value="1"/>
    <eLiterals name="UserDefined" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PrivityScope">
    <eLiterals name="Public"/>
    <eLiterals name="Private" value="1"/>
    <eLiterals name="Static" value="2"/>
    <eLiterals name="WeakDynamic" value="3"/>
    <eLiterals name="StrongDynamic" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Process" eSuperTypes="http://localhost:8080/secbpmn.ecore#//Process">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="OnChainModel" eType="#//BooleanWithNull"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OnChainData">
    <eLiterals name="None"/>
    <eLiterals name="Digest" value="1"/>
    <eLiterals name="Encrypted" value="2"/>
    <eLiterals name="Unencrypted" value="3"/>
    <eLiterals name="Undefined" value="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BlockchainType">
    <eLiterals name="Public" literal="Public"/>
    <eLiterals name="Private" value="1"/>
    <eLiterals name="Undefined" value="-1" literal="Undefined"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataItems" eSuperTypes="http://localhost:8080/secbpmn.ecore#//DataItems">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="OnChainData" eType="#//OnChainData"
        defaultValueLiteral="Undefined" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="http://localhost:8080/secbpmn.ecore#//Task">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="OnChainExecution" eType="#//BooleanWithNull"
        defaultValueLiteral="" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Definitions" eSuperTypes="http://localhost:8080/GMT.ecore#//GMTNamedNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BlockchainType" eType="#//BlockchainType"
        defaultValueLiteral="Undefined" unsettable="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="OnChainModel" eType="#//BooleanWithNull"
        defaultValueLiteral="" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataStore" eSuperTypes="http://localhost:8080/secbpmn.ecore#//DataStore #//DataItems"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataObject" eSuperTypes="http://localhost:8080/secbpmn.ecore#//DataObject #//DataItems"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataInput" eSuperTypes="#//DataItems http://localhost:8080/secbpmn.ecore#//DataInput"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataOutput" eSuperTypes="http://localhost:8080/secbpmn.ecore#//DataOutput #//DataItems"/>
  <eClassifiers xsi:type="ecore:EClass" name="Message" eSuperTypes="#//DataItems http://localhost:8080/secbpmn.ecore#//Message"/>
  <eClassifiers xsi:type="ecore:EClass" name="MessageRef" eSuperTypes="http://localhost:8080/secbpmn.ecore#//MessageRef #//Message"/>
  <eClassifiers xsi:type="ecore:EClass" name="SubProcess" eSuperTypes="http://localhost:8080/secbpmn.ecore#//SubProcess">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="OnChainModel" eType="#//BooleanWithNull"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BooleanWithNull" instanceClassName="java.lang.Boolean">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="EBooleanObject&#xD;&#xA;"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
